; MIIIME Universal Cleaner Configuration
; © 2026 MIIIME

[Launch]
AppName=MIIIME Universal Cleaner

[Settings]
RunAsAdmin=0
ShowFinishMsg=1

[Options]
LogLevel=0

[Advanced]
RetryLimit=10
RetryDelay=50
LogRotationSize=5242880

[CleanupExclude]
01=Dat\AppDat\Roaming\obsidian\IndexedDB
02=Dat\AppDat\Roaming\obsidian\Local Storage
03=Dat\AppDat\Roaming\obsidian\Session Storage
04=Dat\AppDat\Roaming\obsidian\WebStorage
05=Dat\AppDat\Roaming\obsidian\obsidian.json
06=Dat\AppDat\Roaming\obsidian\DIPS
07=Dat\AppDat\Roaming\obsidian\id
08=Dat\AppDat\Roaming\obsidian\Local State
09=Dat\AppDat\Roaming\obsidian\Preferences
10=Dat\AppDat\Roaming\obsidian\Network

[CleanupDelete]
21=App\Obsidian\Squirrel-CheckForUpdate.log
22=App\Obsidian\Squirrel-ProcessStart.log
23=App\Obsidian\Squirrel-Shortcut.log

