; MIIIME Hybrid Launcher Configuration Guide
; ⓒ 2026 MIIIME

; 이 파일은 ANSI 인코딩으로 저장되어야 함.
; This file must be saved in ANSI encoding.

[Launch]
CrashRecovery=0
RunAsAdmin=0
LauncherName=volumouse Miime Launcher
AppName=volumouse
ExeName=volumouse.exe
ExeName64=volumouse.exe
UniqueMutex=volumouse_Miime_Mutex
AllowMultipleInstances=1
WorkDir=
PreRun=
PostRun=

[Directories]
RunPath=App\volumouse
RawDataPath=App\RawDat
ExtPath=App\Ext
DataPath=Dat

[Options]
UseJunction=1
FreezeMode=0
DetectReadOnly=0
LogLevel=0
AddCommand=

[Assets]
AlwaysUpdate=0
01=*|{Run}

[Resources]
SmartSkip=1
FolderIcon=Folder.ico
;Splash=Splash.png
;SplashDuration=1500

[Advanced]
RetryLimit=10
RetryDelay=50
CleanupWait=50
ProcessCheckInterval=200
UserFileBlacklist=|AppData|Desktop|Documents|Downloads|Favorites|Links|Music|Pictures|Saved Games|Searches|Videos|OneDrive|Dropbox|Google Drive|IntelGraphicsProfiles|.oracle_jre_usage|ntuser.dat|ntuser.dat.log1|ntuser.dat.log2|ntuser.ini|
CleanupFolderExclusions=|Microsoft|Windows|Packages|Boot|PerfLogs|
ExitThreshold=2
LogRotationSize=5242880
GuidTrimLen=1
MinOSBuild=0