; MIIIME Hybrid Launcher Configuration Guide
; ⓒ 2026 MIIIME

; 이 파일은 ANSI 인코딩으로 저장되어야 함.
; This file must be saved in ANSI encoding.

[Launch]
CrashRecovery=0
RunAsAdmin=0
LauncherName=GitHubDesktop Miime Launcher
AppName=GitHubDesktop
ExeName=GitHubDesktop.exe
ExeName64=GitHubDesktop.exe
UniqueMutex=GitHubDesktop_Miime_Mutex
AllowMultipleInstances=0
WorkDir=
PreRun=
PostRun=

[Directories]
RunPath=App\GitHubDesktop
RawDataPath=App\RawDat
ExtPath=App\Ext
DataPath=Dat

[Environment]
;PATH01={Env}\System32
;PATH02={Env}\SysWOW64

[Options]
UseJunction=1
FreezeMode=0
DetectReadOnly=0
LogLevel=0
;AddCommand=--user-data-dir="{Dat}\User Data" --disk-cache-dir="{Dat}\Cache"

[ProcessWatch]
01=Update.exe
02=squirrel.exe
03=github.bat

[Registry]
01=HKEY_CURRENT_USER\SOFTWARE\Classes\x-github-desktop-auth
02=HKEY_CURRENT_USER\SOFTWARE\Classes\x-github-client
03=HKEY_CURRENT_USER\SOFTWARE\Classes\github-windows

[RegistryFix]
SmartSkip=1
01=HKEY_CURRENT_USER\SOFTWARE\Classes\x-github-desktop-auth\shell\open\command||"{Run}\GitHubDesktop.exe" --protocol-launcher -- "%1"|REG_SZ
02=HKEY_CURRENT_USER\SOFTWARE\Classes\x-github-client\shell\open\command||"{Run}\GitHubDesktop.exe" --protocol-launcher -- "%1"|REG_SZ
03=HKEY_CURRENT_USER\SOFTWARE\Classes\x-github-windows\shell\open\command||"{Run}\GitHubDesktop.exe" --protocol-launcher -- "%1"|REG_SZ

[CleanupDelete]
SmartSkip=1

01={Roaming}\GitHub Desktop\blob_storage
02={Roaming}\GitHub Desktop\Cache
03={Roaming}\GitHub Desktop\Code Cache
04={Roaming}\GitHub Desktop\DawnGraphiteCache
05={Roaming}\GitHub Desktop\DawnWebGPUCache
06={Roaming}\GitHub Desktop\Dictionaries
07={Roaming}\GitHub Desktop\GPUCache
08={Roaming}\GitHub Desktop\logs
09={Roaming}\GitHub Desktop\Network
10={Roaming}\GitHub Desktop\Service Worker
11={Roaming}\GitHub Desktop\Shared Dictionary
;12={Roaming}\GitHub Desktop\WebStorage
13={Roaming}\GitHub Desktop\.update-id
;14={Roaming}\GitHub Desktop\DIPS
;15={Roaming}\GitHub Desktop\DIPS-wal
16={Roaming}\GitHub Desktop\lockfile
17={Roaming}\GitHub Desktop\SharedStorage
18={Roaming}\GitHub Desktop\SharedStorage-wal
19={Local}\GitHub Desktop\CrashReports

20={Run}\Squirrel-CheckForUpdate.log
21={Run}\Squirrel-Update.log
22={Run}\Squirrel-ProcessStart.log
23={Run}\Squirrel-Shortcut.log
24={Base}\App\SquirrelTemp

25={Programs}\GitHub, Inc
26={StartMenu}\GitHub, Inc
27={CommonPrograms}\GitHub, Inc
28={CommonStartMenu}\GitHub, Inc
29={Programs}\GitHub, Inc.lnk
30={StartMenu}\GitHub, Inc.lnk
31={CommonPrograms}\GitHub, Inc.lnk
32={CommonStartMenu}\GitHub, Inc.lnk
33={Desktop}\GitHub, Inc.lnk

[Resources]
SmartSkip=1
FolderIcon=Folder.ico
;Splash=Splash.png
;SplashDuration=1500

[Advanced]
RetryLimit=10
RetryDelay=50
CleanupWait=50
ProcessCheckInterval=200
UserFileBlacklist=|AppData|Desktop|Documents|Downloads|Favorites|Links|Music|Pictures|Saved Games|Searches|Videos|OneDrive|Dropbox|Google Drive|IntelGraphicsProfiles|.oracle_jre_usage|ntuser.dat|ntuser.dat.log1|ntuser.dat.log2|ntuser.ini|
CleanupFolderExclusions=|Microsoft|Windows|Packages|Boot|PerfLogs|
ExitThreshold=2
LogRotationSize=5242880
GuidTrimLen=1
MinOSBuild=0