; MIIIME Universal Cleaner Configuration
; © 2026 MIIIME

[Launch]
AppName=MIIIME Universal Cleaner

[Settings]
RunAsAdmin=0
ShowFinishMsg=1

[Options]
LogLevel=0

[Advanced]
RetryLimit=10
RetryDelay=50
LogRotationSize=5242880

[CleanupDelete]
01=Dat\AppDat\Roaming\GitHub Desktop\blob_storage
02=Dat\AppDat\Roaming\GitHub Desktop\Cache
03=Dat\AppDat\Roaming\GitHub Desktop\Code Cache
04=Dat\AppDat\Roaming\GitHub Desktop\DawnGraphiteCache
05=Dat\AppDat\Roaming\GitHub Desktop\DawnWebGPUCache
06=Dat\AppDat\Roaming\GitHub Desktop\Dictionaries
07=Dat\AppDat\Roaming\GitHub Desktop\GPUCache
08=Dat\AppDat\Roaming\GitHub Desktop\logs
09=Dat\AppDat\Roaming\GitHub Desktop\Network
10=Dat\AppDat\Roaming\GitHub Desktop\Service Worker
11=Dat\AppDat\Roaming\GitHub Desktop\Shared Dictionary
;12=Dat\AppDat\Roaming\GitHub Desktop\WebStorage
13=Dat\AppDat\Roaming\GitHub Desktop\.update-id
;14=Dat\AppDat\Roaming\GitHub Desktop\DIPS
;15=Dat\AppDat\Roaming\GitHub Desktop\DIPS-wal
16=Dat\AppDat\Roaming\GitHub Desktop\lockfile
17=Dat\AppDat\Roaming\GitHub Desktop\SharedStorage
18=Dat\AppDat\Roaming\GitHub Desktop\SharedStorage-wal
19={Local}\GitHub Desktop\CrashReports

20={Base}\App\GitHubDesktop\Squirrel-CheckForUpdate.log
21={Base}\App\GitHubDesktop\Squirrel-Update.log
22={Base}\App\GitHubDesktop\Squirrel-ProcessStart.log
23={Base}\App\GitHubDesktop\Squirrel-Shortcut.log
24={Base}\App\SquirrelTemp