; MIIIME Hybrid Launcher Configuration Guide
; ⓒ 2026 MIIIME
;
; 이 파일은 ANSI 인코딩으로 저장되어야 합니다.
; This file must be saved in ANSI encoding.

; 원본 프로그램 출처 https://github.com/Tkaixiang/marktext

[Launch]
CrashRecovery=0
RunAsAdmin=0
LauncherName=MarkText MIIIME Launcher
AppName=MarkText
ExeName=marktext.exe
ExeName64=marktext.exe
UniqueMutex=MarkText_MIIIME_Mutex
AllowMultipleInstances=1
WorkDir=
PreRun=
PostRun=

[Directories]
RunPath=App\MarkText
RawDataPath=App\RawDat
ExtPath=App\Ext
DataPath=Dat

[Options]
UseJunction=1
FreezeMode=0
DetectReadOnly=0
LogLevel=0
AddCommand=--user-data-dir="{Dat}\User Data" --disk-cache-dir="{Dat}\Cache" 

[CleanupDelete]
SmartSkip=2

01={Dat}\User Data\blob_storage
02={Dat}\User Data\Cache
03={Dat}\User Data\Code Cache
04={Dat}\User Data\DawnGraphiteCache
05={Dat}\User Data\DawnWebGPUCache
06={Dat}\User Data\Dictionaries
07={Dat}\User Data\GPUCache
08={Dat}\User Data\logs
09={Dat}\User Data\Network
10={Dat}\User Data\Service Worker
11={Dat}\User Data\Shared Dictionary
12={Dat}\User Data\WebStorage
13={Dat}\User Data\.update-id
14={Dat}\User Data\DIPS
15={Dat}\User Data\DIPS-wal
16={Dat}\User Data\lockfile
17={Dat}\User Data\SharedStorage
18={Dat}\User Data\SharedStorage-wal
19={Local}\GitHub Desktop\CrashReports
20={Run}\Squirrel-CheckForUpdate.log
21={Run}\Squirrel-Shortcut.log

22={Programs}\MarkText
23={StartMenu}\MarkText
24={CommonPrograms}\MarkText
25={CommonStartMenu}\MarkText
26={Programs}\MarkText.lnk
27={StartMenu}\MarkText.lnk
28={CommonPrograms}\MarkText.lnk
29={CommonStartMenu}\MarkText.lnk
30={Desktop}\MarkText.lnk

[Resources]
SmartSkip=1
FolderIcon=Folder.ico
;Splash=Splash.png
;SplashDuration=1500

[Advanced]
RetryLimit=10
RetryDelay=50
CleanupWait=50
ProcessCheckInterval=200
UserFileBlacklist=|AppData|Desktop|Documents|Downloads|Favorites|Links|Music|Pictures|Saved Games|Searches|Videos|OneDrive|Dropbox|Google Drive|IntelGraphicsProfiles|.oracle_jre_usage|ntuser.dat|ntuser.dat.log1|ntuser.dat.log2|ntuser.ini|
CleanupFolderExclusions=|Microsoft|Windows|Packages|Boot|PerfLogs|
ExitThreshold=2
LogRotationSize=5242880
GuidTrimLen=1
MinOSBuild=0