; MIIIME Hybrid Launcher Configuration Guide
; ⓒ 2026 MIIIME

; 이 파일은 ANSI 인코딩으로 저장되어야 함.
; This file must be saved in ANSI encoding.

[Launch]
CrashRecovery=0
RunAsAdmin=0
LauncherName=KMPlayer MIIIME Launcher
AppName=KMPlayer64
ExeName=KMPlayer64.exe
ExeName64=KMPlayer64.exe
UniqueMutex=KMPlayer_MIIIME_Mutex
AllowMultipleInstances=1
WorkDir=
PreRun=
PostRun=

[Directories]
RunPath=App\KMPlayer64
RawDataPath=App\RawDat
ExtPath=App\Ext
DataPath=Dat

[Options]
UseJunction=1
FreezeMode=0
DetectReadOnly=0
LogLevel=0
AddCommand=

[ProcessWatch]
01=KMPLoading.exe
02=yt-dlp.exe
03=ffmpeg.exe

[ProcessKill]
;01=crashpad_handler.exe

[Registry]
SmartSkip=0
01=HKEY_CURRENT_USER\Software\KMPlayer
02=HKEY_CURRENT_USER\Software\KMPlayer 64X
03=HKEY_LOCAL_MACHINE\SOFTWARE\Clients\Media\KMPlayer64
04=HKEY_LOCAL_MACHINE\SOFTWARE\RegisteredApplications|KMPlayer 64X

[RegistryRoot]
SmartSkip=0
;01=HKEY_LOCAL_MACHINE\SOFTWARE\RegisteredApplications

[FileWrite]
SmartSkip=1
01={Run}\KMPlayer64.ini|Section:Settings|KEY:SnapshotPath|{Run}\Capture

[Resources]
SmartSkip=1
FolderIcon=Folder.ico
;Splash=Splash.png
;SplashDuration=1500

[Advanced]
RetryLimit=10
RetryDelay=50
CleanupWait=50
ProcessCheckInterval=200
UserFileBlacklist=|AppData|Desktop|Documents|Downloads|Favorites|Links|Music|Pictures|Saved Games|Searches|Videos|OneDrive|Dropbox|Google Drive|IntelGraphicsProfiles|.oracle_jre_usage|ntuser.dat|ntuser.dat.log1|ntuser.dat.log2|ntuser.ini|
CleanupFolderExclusions=|Microsoft|Windows|Packages|Boot|PerfLogs|
ExitThreshold=2
LogRotationSize=5242880
GuidTrimLen=1
MinOSBuild=0