; MIIIME Hybrid Launcher Configuration Guide
; ⓒ 2026 MIIIME

; 이 파일은 ANSI 인코딩으로 저장되어야 함.
; This file must be saved in ANSI encoding.

[Launch]
CrashRecovery=0
RunAsAdmin=0
LauncherName=SoftOrganizer MIIIME Launcher
AppName=SoftOrganizer
ExeName=SoftOrganizer.exe
ExeName64=SoftOrganizer.exe
UniqueMutex=SoftOrganizer_MIIIME_Mutex
AllowMultipleInstances=1
HostInstallCheck=0
ShortcutGuard=1
WorkDir=
PreRun=
PostRun=

[Directories]
RunPath=App\SoftOrganizer64
RawDataPath=App\RawDat
ExtPath=App\Ext
DataPath=Dat

[Environment]
;PATH01={Env}\System32
;PATH02={Env}\SysWOW64

[Options]
UseJunction=1
FreezeMode=0
DetectReadOnly=0
LogLevel=0
AddCommand=

[ProcessWatch]
01=ShellContextMenuInstaller.exe

[ProcessKill]
;01=ShellContextMenuInstaller.exe

[Registry]
SmartSkip=0
01=HKEY_CURRENT_USER\Software\ChemTable Software\Full Uninstall

[RegistryRoot]
SmartSkip=0
01=HKEY_CURRENT_USER\Software\ChemTable Software

[CleanupDelete]
SmartSkip=2
01={Programs}\Soft Organizer.lnk
02={StartMenu}\Soft Organizer.lnk
03={CommonPrograms}\Soft Organizer.lnk
04={CommonStartMenu}\Soft Organizer.lnk
05={Desktop}\Soft Organizer.lnk

[Resources]
SmartSkip=1
FolderIcon=Folder.ico
;Splash=Splash.png
;SplashDuration=1500

[Advanced]
RetryLimit=10
RetryDelay=50
CleanupWait=50
ProcessCheckInterval=200
UserFileBlacklist=|AppData|Desktop|Documents|Downloads|Favorites|Links|Music|Pictures|Saved Games|Searches|Videos|OneDrive|Dropbox|Google Drive|IntelGraphicsProfiles|.oracle_jre_usage|ntuser.dat|ntuser.dat.log1|ntuser.dat.log2|ntuser.ini|
CleanupFolderExclusions=|Microsoft|Windows|Packages|Boot|PerfLogs|
ExitThreshold=2
LogRotationSize=5242880
GuidTrimLen=1
MinOSBuild=0