; MIIIME Hybrid Launcher Configuration Guide
; ⓒ 2026 MIIIME

[Launch]
CrashRecovery=1
RunAsAdmin=0
LauncherName=Notepad++ MIIIME Launcher
AppName=Notepad++
ExeName=notepad++.exe
ExeName64=
UniqueMutex=Notepad++_MIIIME_Mutex
AllowMultipleInstances=1
WorkDir=

[Directories]
RunPath=App\Notepad++
RawDataPath=App\RawDat
ExtPath=App\Ext
DataPath=Dat

[Environment]
;PATH01={Sys}\System32
;PATH02={Sys}\SysWOW64
;PATH03={Base}\..\_MIIIMEEnv\System32
;PATH04={Base}\..\_MIIIMEEnv\SysWOW64

[Options]
UseJunction=1
FreezeMode=0
DetectReadOnly=0
LogLevel=0
AddCommand=

[ProcessWatch]
01=GUP.exe

[Registry]
;01=HKEY_LOCAL_MACHINE\SOFTWARE\Classes\*\shell\ANotepad++64
02=HKEY_LOCAL_MACHINE\SOFTWARE\Notepad++
03=HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Notepad++

[RegistryRoot]
01=HKEY_LOCAL_MACHINE\SOFTWARE\Notepad++
02=HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Notepad++

[RegistryShell]
SmartSkip=0
01=*|Notepad++|Edit with Notepad++|"{Run}\notepad++.exe" "%1"|{Run}\notepad++.exe,0

[CleanupDelete]
Enable=0
01={Run}\change.log
01={Run}\session.xml.inCaseOfCorruption.bak

[Assets]
AlwaysUpdate=0
01=*|{Run}

[Resources]
SmartSkip=1
FolderIcon={Res}\Folder.ico
;Splash={Res}\Splash.png
;SplashDuration=1500

[Advanced]
RetryLimit=10
RetryDelay=50
CleanupWait=50
ProcessCheckInterval=200
SystemFolderExclusions=|Microsoft|Windows|Packages|Boot|PerfLogs|
ExitThreshold=2
LogRotationSize=5242880
GuidTrimLen=1
