; MIIIME Hybrid Launcher Configuration Guide
; ⓒ 2026 MIIIME

; 이 파일은 ANSI 인코딩으로 저장되어야 함.
; This file must be saved in ANSI encoding.

[Launch]
CrashRecovery=0
RunAsAdmin=0
LauncherName=AutoIt3 MIIIME Launcher
AppName=Aut2Exe
ExeName=Aut2Exe.exe
ExeName64=
UniqueMutex=AutoIt3_MIIIME_Mutex
AllowMultipleInstances=1
WorkDir=
PreRun=
PostRun=

[Directories]
RunPath=App\AutoIt3\Aut2Exe

[Advanced]
RetryLimit=10
RetryDelay=50
CleanupWait=50
ProcessCheckInterval=200
UserFileBlacklist=|AppData|Desktop|Documents|Downloads|Favorites|Links|Music|Pictures|Saved Games|Searches|Videos|OneDrive|Dropbox|Google Drive|IntelGraphicsProfiles|.oracle_jre_usage|ntuser.dat|ntuser.dat.log1|ntuser.dat.log2|ntuser.ini|
CleanupFolderExclusions=|Microsoft|Windows|Packages|Boot|PerfLogs|
ExitThreshold=2
LogRotationSize=5242880
GuidTrimLen=1
MinOSBuild=0